server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  profiles:
    active: dev
  cloud:
    config:
      profile: default
  application:
    name: naming-server
  config:
    import: optional:configserver:http://localhost:8888