server:
  port: 8765

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  cloud:
    config:
      profile: default
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true # to make the discovery service names identified in lower-case
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 30