server:
  port: 8100

spring:
  profiles:
    active: dev
  cloud:
    config:
      profile: default
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 30