server:
  port: 8100

spring:
  profiles:
    active: ${ACTIVE_PROFILE:default}
  cloud:
    config:
      profile: default
      fail-fast: true
      enabled: false
      retry:
        initial-interval: 1200
        multiplier: 1.5
        max-attempts: 10000
        max-interval: 1500
  application:
    name: currency-conversion
#  config:
#    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 30