server:
  port: 8000

spring:
  profiles:
    active: dev
  cloud:
    config:
      profile: default
  application:
    name: currency-exchange
  config:
    import: optional:configserver:http://localhost:8888
