name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check the directory
      working-directory: ./NamingServer    

      run: docker build . --file Dockerfile --tag NamingServer:latest
        
